<?php


get_header(); ?>

<div class="container-fluid">

    <article class="row">
           <?php  //query_posts( $query_string . '&posts_per_page=12' );?>
       <?php 
       
        $args = array("post_type" => "post", "orderby" => "date", "order" => "DESC", "post_status" => "publish", "posts_per_page" => "8", "category_name" => "non-classe");
        query_posts($args);
       ?>
            <?php if ( have_posts() ) : ?>

			<?php /* The loop */ ?>
			<?php while ( have_posts() ) : the_post(); ?>
                                <div class="col-lg-3 col-md-6 col-sm-4 col-xs-12 costum-col-md-3">
				<?php get_template_part( 'content', get_post_format() ); ?>
                                </div>
			<?php endwhile; ?>

			<?php twentysixty_paging_nav(); ?>

		<?php else : ?>
			<?php get_template_part( 'content', 'none' ); ?>
		<?php endif; ?>
           
       
    </article>
    <article id="second">   
        <p style="background:#cccccc;">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
         Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        </p>
    </article>
     <article id="third">   
        <p style="background:#cccccc;">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
         Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        </p>
     </article>
     <article>  
         <p style="background:#cccccc;">
           Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
             Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
         </p>
     </article>
     <article id="fifth">  
        <p style="background:#cccccc;">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
         Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed volutpat nisi eget augue euismod, sed fringilla lectus dictum. Integer eu ultricies arcu, sed rutrum justo. Cras hendrerit tincidunt turpis et ornare. Donec eu hendrerit lectus. Vivamus gravida diam eros, ullamcorper scelerisque erat tincidunt vulputate. Mauris risus arcu, eleifend at efficitur in, cursus a lorem. Aliquam ullamcorper euismod tellus sed ullamcorper. 
        </p>
     </article>
<!--<div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">.col-md-4</div>
</div>
<div class="row">
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
</div>
<div class="row">
  <div class="col-md-6">.col-md-6</div>
  <div class="col-md-6">.col-md-6</div>
</div>-->



</div>
<?php get_footer(); ?>